flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.9.2
- cpphs-1.20.4
- haskell-src-exts-1.17.1
- megaparsec-5.2.0
- multiset-0.3.3
- polyparse-1.12
- tf-random-0.5
resolver: ghc-7.10.3
