flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.9.2
- cpphs-1.20.4
- exceptions-0.8.3
- fail-4.9.0.0
- hashable-1.2.6.1
- haskell-src-exts-1.17.1
- hmatrix-0.18.0.0
- integer-logarithms-1.0.2
- megaparsec-5.2.0
- mtl-2.2.1
- multiset-0.3.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- polyparse-1.12
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.5.1
- semigroups-0.18.3
- split-0.2.3.2
- stm-2.4.4.1
- storable-complex-0.2.2
- tagged-0.8.5
- text-1.2.2.2
- tf-random-0.5
- transformers-0.5.4.0
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- vector-0.12.0.1
resolver: ghc-7.10.3
